const BLACK = 30,
  RED = 31,
  GREEN = 32,
  YELLOW = 33,
  BLUE = 34,
  MAGENTA = 35,
  CYAN = 36,
  WHITE = 37,
  RESET = 0

module.exports = {
  TERMINAL_BELL: "\u0007",
  HORIZANTAL_TAB: "\u0009",
  BACKSPACE: "\u0008",
  LINE_FEED: "\u000A",
  VERTICAL_TAB: "\u000B",
  FORM_FEED: "\u000C",
  CARRIAGE_RETURN: "\u000D",
  ESCAPE: "\u001b",
  CURSOR: {
    HOME: "\u001b" + "[H",
    TO: (line, column) => "\u001b" + `[${line};${column}f`,
    UP: rows => "\u001b" + `[${rows}A`,
    DOWN: rows => "\u001b" + `[${rows}B`,
    RIGHT: columns => "\u001b" + `[${columns}C`,
    LEFT: columns => "\u001b" + `[${columns}D`,
    DOWN_FIRST: rows => "\u001b" + `[${rows}E`,
    UP_FIRST: rows => "\u001b" + `[${rows}F`,
    TO_COLUMN: column => "\u001b" + `[${column}G`,
    SAVE: "\u001b" + "[s",
    RESTORE: "\u001b" + "[u",
  },
  ERASE: {
    END_FROM_CURSOR: "\u001b" + "[0J",
    START_FROM_CURSOR: "\u001b" + "[1J",
    CLEAR_SCREEN: "\u001b" + "[2J",
    CURRENT_LINE: "\u001b" + "[2K",
    LINE_END_FROM_CURSOR: "[0K",
    LINE_START_FROM_CURSOR: "[1K",
  },
  GRAPHIC_MODE: {
    RESET: "\u001b" + "[0m",
    BOLD: "\u001b" + "[1m",
    DIM: "\u001b" + "[2m",
    ITALIC: "\u001b" + "[3m",
    UNDERLINE: "\u001b" + "[4m",
    BLINKING: "\u001b" + "[5m",
    INVERSE: "\u001b" + "[7m",
    INVISIBLE: "\u001b" + "[8m",
    STRIKETHROUGH: "\u001b" + "[9m",
  },
  COLOR: {
    TEXT: {
      BLACK: "\u001b" + `[${BLACK}m`,
      RED: "\u001b" + `[${RED}m`,
      GREEN: "\u001b" + `[${GREEN}m`,
      YELLOW: "\u001b" + `[${YELLOW}m`,
      BLUE: "\u001b" + `[${BLUE}m`,
      MAGENTA: "\u001b" + `[${MAGENTA}m`,
      CYAN: "\u001b" + `[${CYAN}m`,
      WHITE: "\u001b" + `[${WHITE}m`,
      RESET: "\u001b" + `[${RESET}m`,
    },
    BACKGROUND: {
      BLACK: "\u001b" + `[${BLACK + 10}m`,
      RED: "\u001b" + `[${RED + 10}m`,
      GREEN: "\u001b" + `[${GREEN + 10}m`,
      YELLOW: "\u001b" + `[${YELLOW + 10}m`,
      BLUE: "\u001b" + `[${BLUE + 10}m`,
      MAGENTA: "\u001b" + `[${MAGENTA + 10}m`,
      CYAN: "\u001b" + `[${CYAN + 10}m`,
      WHITE: "\u001b" + `[${WHITE + 10}m`,
      RESET: "\u001b" + `[${RESET}m`,
    }
  },
}
